# Generated by Django 3.1.2 on 2020-10-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_emp',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('vision', models.CharField(max_length=400)),
                ('mision', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(upload_to='slider')),
            ],
        ),
        migrations.CreateModel(
            name='sliderindex',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=200)),
                ('Imagen', models.ImageField(upload_to='sliderindex')),
            ],
        ),
    ]
